import argparse
import os
import sys

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from analysis import plot_mapping, plot_hap_diff, plot_diff

"""
Usage Guide
===========

This script provides three plotting commands.

1) Trajectory plot (GD vs mapped curves)
----------------------------------------
Command:
  python3 scripts/run_plot.py plot_mapping --genotype {diploid|haploid} --s S --c C --h H [--analytic|--no-analytic] [--grid|--no-grid]

Required flags:
  --genotype   Model type to plot mapped trajectory for: diploid or haploid.
  --s          GD selection coefficient (s_GD).
  --c          GD conversion parameter (c_GD).
  --h          GD dominance parameter (h_GD).

Optional flags:
  --analytic / --no-analytic
    Include or exclude analytic mapping trajectory. Default: include.
  --grid / --no-grid
    Include or exclude grid-search mapping trajectory. Default: include.

Notes:
  - At least one of analytic or grid must be enabled.
  - Mapping parameters are read from CSV results generated by run_mapping.py.

2) Haploid error heatmap
------------------------
Command:
  python3 scripts/run_plot.py plot_hap_diff --h H --method {grid|analytic}

Required flags:
  --h         GD dominance parameter (h_GD) for selecting CSV results.
  --method    Which haploid mapping result to visualize:
              grid     -> from grid-search mapping CSV
              analytic -> from Se analytic mapping CSV

3) Diploid error heatmap
------------------------
Command:
  python3 scripts/run_plot.py plot_diff --h H --regime {fixation|loss|stable|unstable} --method {grid|analytic}

Required flags:
  --h         GD dominance parameter (h_GD) for selecting CSV results.
  --regime    Regime partition used for diploid mapping results.
  --method    Which diploid mapping result to visualize (grid or analytic).

Output:
  All figures are saved under:
    figure/trajectory/
    figure/error_heatmap/
"""


def main():
    parser = argparse.ArgumentParser(description="Run plotting functions")
    subparsers = parser.add_subparsers(dest="command", required=True)

    p_map = subparsers.add_parser("plot_mapping", help="Trajectory plot: GD vs mapped curves")
    p_map.add_argument("--genotype", required=True, choices=["diploid", "haploid"])
    p_map.add_argument("--s", type=float, required=True)
    p_map.add_argument("--c", type=float, required=True)
    p_map.add_argument("--h", type=float, required=True)
    p_map.add_argument("--analytic", dest="analytic", action="store_true", default=True)
    p_map.add_argument("--no-analytic", dest="analytic", action="store_false")
    p_map.add_argument("--grid", dest="grid", action="store_true", default=True)
    p_map.add_argument("--no-grid", dest="grid", action="store_false")

    p_hap = subparsers.add_parser("plot_hap_diff", help="Haploid mapping-error heatmap")
    p_hap.add_argument("--h", type=float, required=True)
    p_hap.add_argument("--method", required=True, choices=["grid", "analytic"])

    p_diff = subparsers.add_parser("plot_diff", help="Diploid mapping-error heatmap")
    p_diff.add_argument("--h", type=float, required=True)
    p_diff.add_argument("--regime", required=True, choices=["fixation", "loss", "stable", "unstable"])
    p_diff.add_argument("--method", required=True, choices=["grid", "analytic"])

    args = parser.parse_args()

    if args.command == "plot_mapping":
        plot_mapping(
            genotype=args.genotype,
            s=args.s,
            c=args.c,
            h=args.h,
            analytic=args.analytic,
            grid=args.grid,
        )
    elif args.command == "plot_hap_diff":
        plot_hap_diff(h=args.h, method=args.method)
    elif args.command == "plot_diff":
        plot_diff(h=args.h, regime=args.regime, method=args.method)


if __name__ == "__main__":
    main()
